chore: allow querying by entry_name by extension name
MaikKlein/ash pull request #574
Opened 2022-02-04 05:13 UTC by pollend

I think it would be useful to query by extension name. 

```
When pLayerName parameter is NULL, only extensions provided by the Vulkan implementation or by implicitly enabled layers are returned. When pLayerName is the name of a layer, the instance extensions provided by that layer are returned.
```

the extensions not explicitly provided will be listed even if they have not been used. you would query the available extensions and then look at those extensions from a predefined list.

2022-02-04 17:11 UTC, MarijnS95 commented
Gah, I have to figure what this `chore` means some day... :(

Perhaps we should just update the `enumerate_instance_extension_properties` API to take an `Option<&CStr>`? That's a breaking change though.

Also, it looks like something went wrong in the commit title and PR title?

2022-02-04 21:58 UTC, pollend commented
> Gah, I have to figure what this `chore` means some day... :(
> 
> Perhaps we should just update the `enumerate_instance_extension_properties` API to take an `Option<&CStr>`? That's a breaking change though.
> 
> Also, it looks like something went wrong in the commit title and PR title?

I've been marking my work using this: https://www.conventionalcommits.org/en/v1.0.0/

I can change the commit when I get back home.

umm yea, I think it make sense to use another method so I don't break the orignal method. too bad you can't just have arguments with defaults.

2022-02-05 00:02 UTC, Ralith commented
> Perhaps we should just update the enumerate_instance_extension_properties API to take an Option<&CStr>?

+1 to this. It's breaking but not super disruptively so, and I don't think anyone expects ash to be semver-stable for long periods at the moment anyway.

2022-02-06 00:41 UTC, Ralith requested changes

2022-02-06 00:41 UTC, Ralith commented on ash/src/entry.rs
> +        p_layer_name: *const c_char
```suggestion
        p_layer_name: Option<&CStr>
```

2022-02-06 18:00 UTC, MarijnS95 commented
> > Gah, I have to figure what this `chore` means some day... :(
> > Perhaps we should just update the `enumerate_instance_extension_properties` API to take an `Option<&CStr>`? That's a breaking change though.
> > Also, it looks like something went wrong in the commit title and PR title?
> 
> I've been marking my work using this: https://www.conventionalcommits.org/en/v1.0.0/

The main point being that `chore` is usually a (mundane) change outside of (public) code: updating version/lock files, changing things in gitattributes/gitmodules, and the like; meta stuff if you wish. This specific prefix doesn't seem documented at that website, they refer to some "Angular" docs where it is not referenced either.

This change is not that. Perhaps it's a fix because we're adding a method that's missing? Perhaps it's a feature because of giving the new "feature" possibility of using it this way?

> umm yea, I think it make sense to use another method so I don't break the orignal method. too bad you can't just have arguments with defaults.

Like @Ralith said - and you've already changed nicely - a breaking change is preferable here. I'll have to think about merge order as we don't have anything breaking right now and I'm not fond of making tons of backport branches, but we can probably come up with a reason to make another breaking release soon anyway.

2022-02-06 18:04 UTC, MarijnS95 requested changes

2022-02-06 18:04 UTC, MarijnS95 commented on ash/src/entry.rs
> +                    },
We have `as_raw_ptr` for this:

https://github.com/MaikKlein/ash/blob/bb02b203391d77e30944f4fc90d7a446474de4c7/ash/src/lib.rs#L55-L67
```suggestion
                    layer_name.as_raw_ptr(),
```

2022-02-06 18:04 UTC, MarijnS95 commented on ash/src/entry.rs
> +        p_layer_name: Option<&CStr>,
```suggestion
        layer_name: Option<&CStr>,
```

We don't commonly use the `p_` prefix for "safe" rusty items.

2022-02-06 18:06 UTC, MarijnS95 commented on ash/src/entry.rs
> +                    },
Welp, thinking about this again this `as_ptr()` is different from a regular borrow of course!

Unfortunately there exists no `.map_or_default()`, but I wonder if the rest of the code uses `.map_or(Default::default(), |s| s.as_ptr())` elsewhere too?

2022-02-19 00:22 UTC, MarijnS95 commented
@pollend I updated the title of this PR (what will show up in the patch) as I have no idea what `entry_name` nor "extension name" have to do with these changes. Let me know if this is correct.

Please also add this to the changelog, then we can merge your patch in time for the breaking 0.36 release somewhere in the - hopefully - next 24 hours.

2022-02-19 09:25 UTC, MarijnS95 approved these changes
Thanks, we're all set now!

2022-02-19 09:30 UTC, merged